### ISSUE TITLE
sjoin failure on larger files

### ISSUE THREAD

**Issue by lucaspanayiotou** [Toblerity/rtree#100]
We are using rtree and getting the following error when working with large files, in our case over 500K rows and 55 columns (18 populated). Our code runs in a docker container using apache. Our developer mentioned that the failure could be due to this being a memory intensive task. Our error is as follows.

2018-01-11 16:36:49,938 - INFO - Processing locations.
2018-01-11 16:36:50,177 - INFO - STARTED: keys_server.CAFL.CAFLKeysLookup.process_locations
2018-01-11 16:36:50,277 - INFO - COMPLETED: keys_server.CAFL.CAFLKeysLookup.process_locations in 0.0s
2018-01-11 16:36:51,860 - INFO - STARTED: keys_server.CAFL.CAFLKeysLookup._get_area_peril_ids
2018-01-11 16:36:51,999 - INFO - COMPLETED: keys_server.CAFL.CAFLKeysLookup._get_area_peril_ids in 0.0s
2018-01-11 16:36:52,000 - INFO - Creating a geodataframe
2018-01-11 16:37:03,246 - INFO - Reprojecting geodataframe
2018-01-11 16:37:48,627 - INFO - Performing spatial join
2018-01-11 16:38:14,539 - ERROR - Keys lookup error: Error in "Index_CreateWithStream": Tools::BufferedFileWriter::open: Cannot open file.: iostream error.
Traceback (most recent call last):
  File "/var/www/oasis/oasis_keys_server/app.py", line 173, in get_keys
    for location_rec in keys_lookup.process_locations(loc_data, mime_type=mime_type):
  File "/var/www/oasis/keys_server/CAFL/CAFLKeysLookup.py", line 74, in process_locations
    for geo_df_row in self._get_area_peril_ids(loc_df, include_context=True):
  File "/var/www/oasis/keys_server/CAFL/CAFLKeysLookup.py", line 188, in _get_area_peril_ids
    pointInPolys = sjoin(points, self.polys, how='left', op='within')
  File "/usr/local/lib/python2.7/dist-packages/geopandas/tools/sjoin.py", line 69, in sjoin
    tree_idx = rtree.index.Index(stream)
  File "/usr/local/lib/python2.7/dist-packages/rtree/index.py", line 264, in __init__
    self.handle = self._create_idx_from_stream(stream)
  File "/usr/local/lib/python2.7/dist-packages/rtree/index.py", line 728, in _create_idx_from_stream
    return IndexStreamHandle(self.properties.handle, stream)
  File "/usr/local/lib/python2.7/dist-packages/rtree/index.py", line 854, in __init__
    self._ptr = self._create(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rtree/core.py", line 28, in check_void
    raise RTreeError(msg)
RTreeError: Error in "Index_CreateWithStream": Tools::BufferedFileWriter::open: Cannot open file.: iostream error

**Comment by sr-murthy** [comment]
It is the `sjoin` operation which is failing, and we think it has to do with the size of the `points` variable which is constructed from a pandas dataframe `loc_data` (which may contain 1M rows or more):
            ....
            geometry = [Point(float(x), float(y)) for x, y in zip(loc_data.LON, loc_data.LAT)]
        points = GeoDataFrame(
            loc_data, crs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs", geometry=geometry
        )
            ...
            points = points.to_crs(self.polys.crs)
            ...
            pointInPolys = sjoin(points, self.polys, how='left', op='within')
            ...

Here `polys` is a geopandas dataframe containing approximately 3.1 million polygons.

**Comment by villanuevab** [comment]
Hello. I am seeing a similar issue with `sjoin(..., op='contains')`. Is the suggested solution for this to simply loop over slices of the dataframe, `sjoin()`, and concatenate the results after?

**Comment by hobu** [comment]
I don't know anything about geopandas. If you can construct an example that demonstrates the issue I might be able to figure out where it is.
