### ISSUE TITLE
Python 3* compatibility

### ISSUE THREAD

**Issue by TheChymera** [Toblerity/rtree#111]
Does the latest release (0.8.3) support Python3* all the way up to 3.6?

**Comment by TheChymera** [comment]
according to the .travis.yaml for the tag it only goes up to 3.5. Was that just untested or do you know for a fact it has issues on 3.6?

**Comment by hobu** [comment]
Just untested.

**Comment by TheChymera** [comment]
@hobu 

Ok, it seems two test items fail with Python 3.6. Does this look like a version incompatibility to you, or is it something else?

```
>>> Emerging (1 of 1) sci-libs/Rtree-0.8.3::local
 * Rtree-0.8.3.tar.gz BLAKE2B SHA512 size ;-) ...                                                 [ ok ]
>>> Unpacking source...
>>> Unpacking Rtree-0.8.3.tar.gz to /var/tmp/portage/sci-libs/Rtree-0.8.3/work
>>> Source unpacked in /var/tmp/portage/sci-libs/Rtree-0.8.3/work
>>> Preparing source in /var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3 ...
 * python2_7: running distutils-r1_run_phase distutils-r1_python_compile
python2.7 setup.py build
running build
running build_py
creating /var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3-python2_7/lib/rtree
copying rtree/index.py -> /var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3-python2_7/lib/rtree
copying rtree/core.py -> /var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3-python2_7/lib/rtree
copying rtree/__init__.py -> /var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3-python2_7/lib/rtree
warning: build_py: byte-compiling is disabled, skipping.

 * python3_6: running distutils-r1_run_phase distutils-r1_python_compile
python3.6 setup.py build -j 5
running build
running build_py
creating /var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3-python3_6/lib/rtree
copying rtree/index.py -> /var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3-python3_6/lib/rtree
copying rtree/core.py -> /var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3-python3_6/lib/rtree
copying rtree/__init__.py -> /var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3-python3_6/lib/rtree
warning: build_py: byte-compiling is disabled, skipping.

>>> Source compiled.
>>> Test phase: sci-libs/Rtree-0.8.3
 * python2_7: running distutils-r1_run_phase python_test
========================================== test session starts ==========================================
platform linux2 -- Python 2.7.15, pytest-3.8.0, py-1.5.4, pluggy-0.7.1 -- /usr/bin/python2.7
cachedir: .pytest_cache
rootdir: /var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3, inifile:
plugins: pep8-1.0.6, forked-0.2, cov-2.5.1
collecting ... collected 10 items

tests/test_bounds.txt::test_bounds.txt PASSED                                                     [ 10%]
tests/test_customStorage.txt::test_customStorage.txt PASSED                                       [ 20%]
tests/test_doctests.py::test_suite PASSED                                                         [ 30%]
tests/test_index.py::IndexTests::test_stream_input PASSED                                         [ 40%]
tests/test_index_doctests.txt::test_index_doctests.txt PASSED                                     [ 50%]
tests/test_misc.txt::test_misc.txt PASSED                                                         [ 60%]
tests/test_pickle.py::TestPickling::test_index PASSED                                             [ 70%]
tests/test_pickle.py::TestPickling::test_property PASSED                                          [ 80%]
tests/test_properties.txt::test_properties.txt PASSED                                             [ 90%]
tests/test_z_cleanup.txt::test_z_cleanup.txt PASSED                                               [100%]

======================================= 10 passed in 0.16 seconds =======================================
 * python3_6: running distutils-r1_run_phase python_test
========================================== test session starts ==========================================
platform linux -- Python 3.6.6, pytest-3.8.0, py-1.5.4, pluggy-0.7.1 -- /usr/bin/python3.6
cachedir: .pytest_cache
rootdir: /var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3, inifile:
plugins: pep8-1.0.6, forked-0.2, cov-2.5.1
collecting ... collected 10 items

tests/test_bounds.txt::test_bounds.txt PASSED                                                     [ 10%]
tests/test_customStorage.txt::test_customStorage.txt PASSED                                       [ 20%]
tests/test_doctests.py::test_suite PASSED                                                         [ 30%]
tests/test_index.py::IndexTests::test_stream_input PASSED                                         [ 40%]
tests/test_index_doctests.txt::test_index_doctests.txt PASSED                                     [ 50%]
tests/test_misc.txt::test_misc.txt FAILED                                                         [ 60%]
tests/test_pickle.py::TestPickling::test_index PASSED                                             [ 70%]
tests/test_pickle.py::TestPickling::test_property PASSED                                          [ 80%]
tests/test_properties.txt::test_properties.txt PASSED                                             [ 90%]
tests/test_z_cleanup.txt::test_z_cleanup.txt FAILED                                               [100%]

=============================================== FAILURES ================================================
________________________________________ [doctest] test_misc.txt ________________________________________
005     >>> r = Rtree('overwriteme')
006     >>> del r
007     >>> r = Rtree('overwriteme', overwrite=True)
008 
009 
010 the default serializer is pickle, can use any by overriding dumps, loads
011 
012     >>> r = Rtree()
013     >>> some_data = {"a": 22, "b": [1, "ccc"]}
014     >>> try:
UNEXPECTED EXCEPTION: TypeError('{"a": 22, "b": [1, "ccc"]}',)
Traceback (most recent call last):

  File "/usr/lib64/python3.6/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)

  File "<doctest test_misc.txt[6]>", line 5, in <module>

  File "/var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3/rtree/index.py", line 374, in insert
    size, data, pyserialized = self._serialize(obj)

  File "/var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3/rtree/index.py", line 334, in _serialize
    d = ctypes.create_string_buffer(serialized)

  File "/usr/lib64/python3.6/ctypes/__init__.py", line 63, in create_string_buffer
    raise TypeError(init)

TypeError: {"a": 22, "b": [1, "ccc"]}

/var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3/tests/test_misc.txt:14: UnexpectedException
_____________________________________ [doctest] test_z_cleanup.txt ______________________________________
003     >>> files = ['defaultidx.dat','defaultidx.idx',
004     ...          'pagesize3.dat','pagesize3.idx',
005     ...          'testing.dat','testing.idx',
006     ...          'custom.data','custom.index',
007     ...          'streamed.idx','streamed.dat',
008     ...          'gilename䔀abc.dat','gilename䔀abc.idx',
009     ...          'overwriteme.idx', 'overwriteme.dat']
010     >>> import os
011     >>> import time
012     >>> for f in files:
UNEXPECTED EXCEPTION: FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):

  File "<doctest test_z_cleanup.txt[5]>", line 3, in <module>

FileNotFoundError: [Errno 2] No such file or directory: 'gilename䔀abc.dat'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib64/python3.6/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)

  File "<doctest test_z_cleanup.txt[5]>", line 6, in <module>

FileNotFoundError: [Errno 2] No such file or directory: 'gilename䔀abc.dat'

/var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3/tests/test_z_cleanup.txt:12: UnexpectedException
=========================================== warnings summary ============================================
/var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3/tests/test_pickle.py:11: DeprecationWarning: Please use assertNotEqual instead.
  self.assertNotEquals(idx.handle, unpickled.handle)
/var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3/tests/test_pickle.py:13: DeprecationWarning: Please use assertEqual instead.
  unpickled.properties.as_dict())
/var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3/tests/test_pickle.py:14: DeprecationWarning: Please use assertEqual instead.
  self.assertEquals(idx.interleaved, unpickled.interleaved)

/var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3/tests/test_pickle.py:19: DeprecationWarning: Please use assertNotEqual instead.
  self.assertNotEquals(p.handle, unpickled.handle)
/var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3/tests/test_pickle.py:20: DeprecationWarning: Please use assertEqual instead.
  self.assertEquals(p.as_dict(), unpickled.as_dict())

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================ 2 failed, 8 passed, 5 warnings in 0.35 seconds =============================
 * ERROR: sci-libs/Rtree-0.8.3::local failed (test phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  124:  Called src_test
 *   environment, line 2707:  Called distutils-r1_src_test
 *   environment, line  959:  Called _distutils-r1_run_foreach_impl 'python_test'
 *   environment, line  410:  Called python_foreach_impl 'distutils-r1_run_phase' 'python_test'
 *   environment, line 2240:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'python_test'
 *   environment, line 1613:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'python_test'
 *   environment, line 1611:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'python_test'
 *   environment, line  622:  Called distutils-r1_run_phase 'python_test'
 *   environment, line  890:  Called python_test
 *   environment, line 2609:  Called die
 * The specific snippet of code:
 *       pytest --verbose || die
 * 
 * If you need support, post the output of `emerge --info '=sci-libs/Rtree-0.8.3::local'`,
 * the complete build log and the output of `emerge -pqv '=sci-libs/Rtree-0.8.3::local'`.
 * The complete build log is located at '/var/tmp/portage/sci-libs/Rtree-0.8.3/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-libs/Rtree-0.8.3/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3'
 * S: '/var/tmp/portage/sci-libs/Rtree-0.8.3/work/Rtree-0.8.3'
```

**Comment by hobu** [comment]
Both of those failures are on a unicode filename test. Unclear what exactly the issue might be without digging.

**Comment by TheChymera** [comment]
@hobu sadly there aren't any newer releases. Could you make one ? :)

**Comment by hobu** [comment]
master builds all the way to 3.7 https://travis-ci.org/Toblerity/rtree

We're waiting on the relicense to settle down before issuing the release #97 I don't have a time frame because I don't know the status of who has or has not yet agreed to the relicense.

**Comment by TheChymera** [comment]
Ok, sadly I can't wait, so I'll have to package a snapshot :(

Is there any recent commit you would recommend as least unstable?

**Comment by TheChymera** [comment]
Ok, I have packaged the latest commit `c6437a8ae182cb58aef1d0a4465bfc0c6f75b273` as it adds python3.7 support, and has passed all tests on all python implenemtations on my machine.

Just for the record, this will be [listed in Gentoo Linux as `=sci-libs/Rtree.0.8.3_p20180802`](https://github.com/gentoo/gentoo/pull/10049).

Many Thanks!
