### ISSUE TITLE
How do I install Rtree

### ISSUE THREAD

**Issue by devlocalca** [Toblerity/rtree#146]
I type:  `$pip install Rtree` , and I get this error message, how do I install Rtree please?

Can someone please send me instructions for installation on:
```
1. Windows 10
2. RHEL 8.x
3. CentOS 8.x
```

I need it installed on all three environments please.

---
```
PS C:\Users\<user>> pip install Rtree
Collecting Rtree
  Using cached Rtree-0.9.4.tar.gz (62 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\apps\python\3.8.1\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\<user>\\AppData\\Local\\Temp\\pip-install-lxb1cib8\\Rtree\\setup.py'"'"'; __file__='"'"'C:\\Users\\<user>\\AppData\\Local\\Temp\\pip-install-lxb1cib8\\Rtree\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\<user>\AppData\Local\Temp\pip-install-lxb1cib8\Rtree\pip-egg-info'
         cwd: C:\Users\<user>\AppData\Local\Temp\pip-install-lxb1cib8\Rtree\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\<user>\AppData\Local\Temp\pip-install-lxb1cib8\Rtree\setup.py", line 3, in <module>
        import rtree
      File "C:\Users\<user>\AppData\Local\Temp\pip-install-lxb1cib8\Rtree\rtree\__init__.py", line 1, in <module>
        from .index import Rtree
      File "C:\Users\<user>\AppData\Local\Temp\pip-install-lxb1cib8\Rtree\rtree\index.py", line 6, in <module>
        from . import core
      File "C:\Users\<user>\AppData\Local\Temp\pip-install-lxb1cib8\Rtree\rtree\core.py", line 126, in <module>
        raise OSError("could not find or load %s" % lib_name)
    OSError: could not find or load spatialindex_c-64.dll
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.```

**Comment by TanguyCazalets** [comment]
Hey, 
The error message is confusing.
For me the solution was to first install libspatialindex
`sudo apt install libspatialindex-dev`

**Comment by FaviG** [comment]
conda install -c conda-forge libspatialindex
conda install -c conda-forge rtree

**Comment by efojs** [comment]
Came here with same problem, I don't use `conda` and could not install `libspatialindex` with `pipenv`:
```
# macOS Mojave 10.14.5
# python 3.7.4 (via pyenv)

Error: Command "python setup.py egg_info" failed with error code 1 in /var/folders/r7/2sx1wsvx0gj5x43wkmymg61w0000gq/T/tmpn09357tzbuild/rtree/
```




Found [solution](http://macappstore.org/spatialindex/) — install `spatialindex` via Homebrew:
- `brew install spatialindex`

Then `pipenv install rtree` succeeded and now `geopandas` works smoothly
Hope it'll help

**Comment by benjaminBrownlee** [comment]
Is there a reason that the conda install isn't working on debian based systems anymore? I have an old conda environment on my Ubuntu machine that has a working installation of rtree but I can't install rtree on a new environment without the apt packages.

**Comment by anishpatelwork** [comment]
@efojs this solution worked perfectly for me. Thanks for posting.

**Comment by Abeautifulsnow** [comment]
If you are using centos, you can install `spatialindex` via `yum`:
```bash
sudo yum -y install spatialindex.x86_64 spatialindex-devel.x86_64
```
And then, you can install `rtree` successfully.

**Comment by hobu** [comment]
Please try 0.9.6 which include libspatialindex builds in wheels
