### ISSUE TITLE
`pip install rtree` still failing on 0.9.4 on windows

### ISSUE THREAD

**Issue by maboualidev** [Toblerity/rtree#167]
This is still 
(testenv2) C:\Users\mabouali\AppData\Local\pip>pip install rtree
Collecting rtree
  Downloading Rtree-0.9.4.tar.gz (62 kB)
     |████████████████████████████████| 62 kB 216 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'E:\Users\mabouali\miniconda3\envs\testenv2\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mabouali\\AppData\\Local\\Temp\\pip-install-rfjh1w4e\\rtree\\setup.py'"'"'; __file__='"'"'C:\\Users\\mabouali\\AppData\\Local\\Temp\\pip-install-rfjh1w4e\\rtree\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\mabouali\AppData\Local\Temp\pip-pip-egg-info-6d_fm1ag'
         cwd: C:\Users\mabouali\AppData\Local\Temp\pip-install-rfjh1w4e\rtree\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mabouali\AppData\Local\Temp\pip-install-rfjh1w4e\rtree\setup.py", line 3, in <module>
        import rtree
      File "C:\Users\mabouali\AppData\Local\Temp\pip-install-rfjh1w4e\rtree\rtree\__init__.py", line 1, in <module>
        from .index import Rtree
      File "C:\Users\mabouali\AppData\Local\Temp\pip-install-rfjh1w4e\rtree\rtree\index.py", line 6, in <module>
        from . import core
      File "C:\Users\mabouali\AppData\Local\Temp\pip-install-rfjh1w4e\rtree\rtree\core.py", line 126, in <module>
        raise OSError("could not find or load %s" % lib_name)
    OSError: could not find or load spatialindex_c-64.dll
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Yumin-Sun-00** [comment]
I have the same problem

**Comment by silvadealmeida** [comment]
same with googleColab
Collecting Rtree
  Using cached https://files.pythonhosted.org/packages/56/6f/f1e91001d5ad9fa9bed65875152f5a1c7955c5763168cae309546e6e9fda/Rtree-0.9.4.tar.gz
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by nshahpazov** [comment]
Having the same issue.

**Comment by Keou0007** [comment]
Failing on mac and linux also with slightly different errors

<details><summary>macOS</summary>

```
Collecting rtree
  Downloading Rtree-0.9.4.tar.gz (62 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-vv7qrbxd/rtree/setup.py'"'"'; __file__='"'"'/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-vv7qrbxd/rtree/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-pip-egg-info-b9ee5b11
         cwd: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-vv7qrbxd/rtree/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-vv7qrbxd/rtree/setup.py", line 3, in <module>
        import rtree
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-vv7qrbxd/rtree/rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-vv7qrbxd/rtree/rtree/index.py", line 6, in <module>
        from . import core
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-vv7qrbxd/rtree/rtree/core.py", line 143, in <module>
        rt.Error_GetLastErrorNum.restype = ctypes.c_int
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
        func = self.__getitem__(name)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: dlsym(RTLD_DEFAULT, Error_GetLastErrorNum): symbol not found
    ----------------------------------------
```
</details>

<details><summary>Linux</summary>

```
Collecting rtree
  Downloading Rtree-0.9.4.tar.gz (62 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/hostedtoolcache/Python/3.6.12/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bodubagd/rtree/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bodubagd/rtree/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5y4oyawv
         cwd: /tmp/pip-install-bodubagd/rtree/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bodubagd/rtree/setup.py", line 3, in <module>
        import rtree
      File "/tmp/pip-install-bodubagd/rtree/rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "/tmp/pip-install-bodubagd/rtree/rtree/index.py", line 6, in <module>
        from . import core
      File "/tmp/pip-install-bodubagd/rtree/rtree/core.py", line 143, in <module>
        rt.Error_GetLastErrorNum.restype = ctypes.c_int
      File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
        func = self.__getitem__(name)
      File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: /opt/hostedtoolcache/Python/3.6.12/x64/bin/python: undefined symbol: Error_GetLastErrorNum

```
</details>

**Comment by Keou0007** [comment]
I'm not sure this will be fixed because the libspatialindex requirement is a C library that is not available on pypi and so can't be installed by pip. So unless someone makes it into a pypi package, the only options seem to be to install libspatialindex manually before installing rtree with pip, or install rtree with conda, since anaconda has a libspatialindex package that can be installed concurrently.

**Comment by hobu** [comment]
Pleas try 0.9.6
