### ISSUE TITLE
libspatialindex bundling not working correctly

### ISSUE THREAD

**Issue by zoharby** [Toblerity/rtree#173]
I'm trying to use rtree in a pySpark environment (GCP dataproc cluster). Was happy to find out you just released 0.9.5 which should solve the headache of the libspatialindex dependency, and decided to give it a try.
I added Rtree==0.95 to the pip packages of the cluster, but it seems it's unable to locate the bundled libspatialindex properly:
```
>>> import rtree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/default/lib/python3.7/site-packages/rtree/__init__.py", line 9, in <module>
    from .index import Rtree, Index  # noqa
  File "/opt/conda/default/lib/python3.7/site-packages/rtree/index.py", line 6, in <module>
    from . import core
  File "/opt/conda/default/lib/python3.7/site-packages/rtree/core.py", line 77, in <module>
    rt.Error_GetLastErrorNum.restype = ctypes.c_int
  File "/opt/conda/default/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "/opt/conda/default/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: Error_GetLastErrorNum
```

Python version:
```
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux
```

The same thing happens in a pure Python 3 env:
```
Python 3.5.3 (default, Nov 18 2020, 21:09:16)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rtree import Rtree, index
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zohar/.local/lib/python3.5/site-packages/rtree/__init__.py", line 9, in <module>
    from .index import Rtree, Index  # noqa
  File "/home/zohar/.local/lib/python3.5/site-packages/rtree/index.py", line 6, in <module>
    from . import core
  File "/home/zohar/.local/lib/python3.5/site-packages/rtree/core.py", line 77, in <module>
    rt.Error_GetLastErrorNum.restype = ctypes.c_int
  File "/usr/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python3: undefined symbol: Error_GetLastErrorNum
```

Any idea why it fails, and whether I can overcome it with some environment variable setting?

**Comment by zoharby** [comment]
Hmm, I see that the wheels were not really uploaded to PyPi, so I guess it simply installs from source without libspatialindex.
Any idea when the wheels will be pushed to PyPi?

**Comment by hobu** [comment]
Please try 0.9.6

**Comment by zoharby** [comment]
Works like a charm :)
Thanks!
