### ISSUE TITLE
Rtree and Pyinstaller: undefined symbol: Error_GetLastErrorNum

### ISSUE THREAD

**Issue by GabrieleMaurina** [Toblerity/rtree#187]
Hi,
I know this has been asked before, but I cannot find a solution that works for me.

Rtree 0.9.7 (installed with pip)
Pyinstaller 4.3
Python 3.8
Linux Fedora32 (but I need a solution to work on Windows 10 as well)

Minimal code example:

example.py
```python
import rtree
rtree.index.Index()
print('test')
```

build.py
```python
from os import system
from PyInstaller.utils.hooks import collect_dynamic_libs

rtree_dependencies = collect_dynamic_libs('rtree')

cmd = []
cmd.append('pyinstaller')
cmd.append('-F')
cmd.append('-w')
cmd.append('-n Example')
for src,des in rtree_dependencies:
    cmd.append(f'--add-binary "{src}:{des}"')
cmd.append('example.py')

system(' '.join(cmd))
```

When I run build.py it builds the executable, but when I run the executable I get this error:
```
Traceback (most recent call last):
  File "example.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "rtree/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "rtree/index.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "rtree/core.py", line 75, in <module>
  File "rtree/finder.py", line 121, in load
OSError: Could not load libspatialindex_c library
[70701] Failed to execute script example
```

The libraries "libspatialindex_c.so" and "libspatialindex.so" are in my system and are found by collect_dynamic_libs. But still it does not work.

The generated spec file looks like this:
```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['example.py'],
             pathex=['/workspace/example'],
             binaries=[('.local/lib/python3.8/site-packages/rtree/lib/libspatialindex_c.so', 'rtree/lib'), ('.local/lib/python3.8/site-packages/rtree/lib/libspatialindex.so', 'rtree/lib')],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='Example',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False )
```

**Comment by GabrieleMaurina** [comment]
I found a solution in case someone stubles upon the same issue in the future.

The pyinstaller function `collect_dynamic_libs('rtree')` finds only:

- rtree/lib/libspatialindex_c.so
- rtree/lib/libspatialindex.so

but does not find:

- Rtree.libs/libspatialindex-bf66e7c6.so.6.1.1

If you use Windows or Linux they might have different names.

My solution was to manually add the missing binaries to the list of binaries bundled by pyinstaller. Like so:
```python
from os import system
from PyInstaller.utils.hooks import collect_dynamic_libs

rtree_dependencies = collect_dynamic_libs('rtree')
rtree_dependencies.append((

#           use the right absolute path here

    '<path to python packages>/Rtree.libs/libspatialindex-bf66e7c6.so.6.1.1',
    'Rtree.libs'))

cmd = []
cmd.append('pyinstaller')
cmd.append('-F')
cmd.append('-w')
cmd.append('-n Example')
for src,des in rtree_dependencies:
    cmd.append(f'--add-binary "{src}:{des}"')
cmd.append('example.py')

system(' '.join(cmd))
```

I am not sure if this is a problem of Rtree, or rather a problem of Pyinstaller. Perhaps a proper hook for Pyinstaller could be included inside Rtree package so that it would always work.
