### ISSUE TITLE
typing_extensions now required

### ISSUE THREAD

**Issue by hobu** [Toblerity/rtree#242]
Conda Forge build is failing to run the tests for Python 3.7. Can you take a look @adamjstewart? I believe you changed this stuff.

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=486292&view=logs&jobId=517fe804-fa30-5dc2-1413-330699242c05&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412

```
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/rtree_1649130106502/test_tmp/run_test.py", line 10, in <module>
    from rtree import index
  File "/home/conda/feedstock_root/build_artifacts/rtree_1649130106502/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.7/site-packages/rtree/__init__.py", line 9, in <module>
    from .index import Index, Rtree  # noqa
  File "/home/conda/feedstock_root/build_artifacts/rtree_1649130106502/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.7/site-packages/rtree/index.py", line 15, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
Tests failed for rtree-1.0.0-py37h0b55af0_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
```

We have the following in `setup.cfg`, but it does not seem to be taking effect:

```
python_requires = >=3.7
install_requires =
    typing_extensions>=3.7;python_version<'3.8'
```

**Comment by hobu** [comment]
Actually, I think this is just a recipe that needs updating. Sorry for hte noise @adamjstewart
