### ISSUE TITLE
Cannot append idx_extension or dat_extension to python strings

### ISSUE THREAD

**Issue by ARF1** [Toblerity/rtree#70]
Presumably related to #69.

On
```
Python 3.4.4 |Continuum Analytics, Inc.| (default, Mar  4 2016, 15:23:09) [MSC v
.1600 32 bit (Intel)] on win32
```
the `dat_extension` and `idx_extension` properties cannot be appended to python strings:
```
Traceback (most recent call last):
  File "C:\Users\ARF1\Documents\Programming\gis\module1.py", line 243, in
<module>
    run(args)
  File "C:\Users\ARF1\Documents\Programming\gis\module1.py", line 140, in
run
    filename = 'test' + rtree_props.dat_extension
TypeError: Can't convert 'bytes' object to str implicitly
Press any key to continue . . .
```

**Comment by hobu** [comment]
I think you need the locales available. I don't know what that means for Windows, however. Closing for now.
