### ISSUE TITLE
pip install fails with "AttributeError: /usr/bin/python2: undefined symbol: Error_GetLastErrorNum"

### ISSUE THREAD

**Issue by traverseda** [Toblerity/rtree#75]
```
Collecting rtree (from trimesh[all])
  Using cached Rtree-0.8.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Bh7x0q/rtree/setup.py", line 4, in <module>
        import rtree
      File "rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "rtree/index.py", line 6, in <module>
        from . import core
      File "rtree/core.py", line 110, in <module>
        rt.Error_GetLastErrorNum.restype = ctypes.c_int
      File "/usr/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
        func = self.__getitem__(name)
      File "/usr/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: /usr/bin/python2: undefined symbol: Error_GetLastErrorNum
```

**Comment by davidedelvento** [comment]
I guess this is the same as #64

**Comment by hobu** [comment]
#74 is the leading ticket on these path issues.
