### ISSUE TITLE
egg_info failed with error code 1 on Debian

### ISSUE THREAD

**Issue by raphadasilva** [Toblerity/rtree#78]
Morning !

I'm sorry if a similar issue was already opened, but I didn't find anything title close to my problem.

I'm using Linux SMP Debian 3.16.7-ckt25-2 (kernel release 3.16.0-4-amd64) on my laptop, and here's the log when I run a sudo pip3 install rtree : 

```
Downloading/unpacking rtree
  Downloading Rtree-0.8.2.tar.gz (55kB): 55kB downloaded
  Running setup.py (path:/tmp/pip-build-06qzn7u1/rtree/setup.py) egg_info for package rtree
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-06qzn7u1/rtree/setup.py", line 4, in <module>
        import rtree
      File "/tmp/pip-build-06qzn7u1/rtree/rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "/tmp/pip-build-06qzn7u1/rtree/rtree/index.py", line 6, in <module>
        from . import core
      File "/tmp/pip-build-06qzn7u1/rtree/rtree/core.py", line 110, in <module>
        rt.Error_GetLastErrorNum.restype = ctypes.c_int
      File "/usr/lib/python3.4/ctypes/__init__.py", line 364, in __getattr__
        func = self.__getitem__(name)
      File "/usr/lib/python3.4/ctypes/__init__.py", line 369, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: /usr/bin/python3: undefined symbol: Error_GetLastErrorNum
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-06qzn7u1/rtree/setup.py", line 4, in <module>

    import rtree

  File "/tmp/pip-build-06qzn7u1/rtree/rtree/__init__.py", line 1, in <module>

    from .index import Rtree

  File "/tmp/pip-build-06qzn7u1/rtree/rtree/index.py", line 6, in <module>

    from . import core

  File "/tmp/pip-build-06qzn7u1/rtree/rtree/core.py", line 110, in <module>

    rt.Error_GetLastErrorNum.restype = ctypes.c_int

  File "/usr/lib/python3.4/ctypes/__init__.py", line 364, in __getattr__

    func = self.__getitem__(name)

  File "/usr/lib/python3.4/ctypes/__init__.py", line 369, in __getitem__

    func = self._FuncPtr((name_or_ordinal, self))

AttributeError: /usr/bin/python3: undefined symbol: Error_GetLastErrorNum

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-06qzn7u1/rtree
Storing debug log for failure in /root/.pip/pip.log
```
I'm sorry, it's quite long... But hope you could help !

Thanks in advance and have a nice day.

**Comment by hobu** [comment]
You do not have a recent enough version of libspatialindex installed.

**Comment by raphadasilva** [comment]
I'm sorry to insist but I just checked my package manager, and got the 1.81-3 version of libspatialindex3... Are you sure this one is already obsolete ?
