### ISSUE TITLE
Issue with RTree while using GeoPandas

### ISSUE THREAD

**Issue by GISConsortium** [Toblerity/rtree#93]
I am trying to work on geopandas, python 2.7, on windows environment. 

I am implementing example provided at: https://automating-gis-processes.github.io/2016/Lesson3-spatial-join.html

But I got the below-mentioned issue for R-tree while using geo-pandas.
All lines are working fine, except for the last one.

My Script:

import geopandas as gpd
fp=r"C:\Shared\Test_Data\geopandastest\Vaestotietoruudukko_2015\Vaestotietoruudukko_2015.shp"
pop = gpd.read_file(fp)
addr_fp =r'C:\Shared\Test_Data\geopandastest\address\addresses_epsg3879.shp'
addresses = gpd.read_file(addr_fp)
join = gpd.sjoin(addresses, pop, how="inner", op="within")

I am getting this error:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 313, in 'calling callback function'
  File "C:\Python27\lib\site-packages\rtree\index.py", line 717, in py_next_item
    p_dimension[0] = dimension
ValueError: NULL pointer access
Traceback (most recent call last):
  Python Shell, prompt 25, line 1
  File "C:\Python27\Lib\site-packages\geopandas\tools\sjoin.py", line 69, in sjoin
    tree_idx = rtree.index.Index(stream)
  File "C:\Python27\Lib\site-packages\rtree\index.py", line 264, in __init__
    self.handle = self._create_idx_from_stream(stream)
  File "C:\Python27\Lib\site-packages\rtree\index.py", line 728, in _create_idx_from_stream
    return IndexStreamHandle(self.properties.handle, stream)
  File "C:\Python27\Lib\site-packages\rtree\index.py", line 854, in __init__
    self._ptr = self._create(*args, **kwargs)
  File "C:\Python27\Lib\site-packages\rtree\core.py", line 28, in check_void
    raise RTreeError(msg)
rtree.core.RTreeError: Error in "Index_CreateWithStream": IllegalArgumentException: RTree::BulkLoader::bulkLoadUsingSTR: Empty data stream given.

**Comment by sgillies** [comment]
I see that you have created an identical issue at https://github.com/geopandas/geopandas/issues/625. I'm going to close this one and watch the other.

**Comment by GISConsortium** [comment]
@sgillies : but I think this is a issue with Rtree, and not with geopandas.
