### ISSUE TITLE
Issue calling rtree.index.Index(object)

### ISSUE THREAD

**Issue by GISConsortium** [Toblerity/rtree#94]
import rtree
stream=(8, (-3.5731852365209757, 0.7485694484767316, -2.9501297095816534, 1.5179486218942282), None)
tree_idx = rtree.index.Index(stream)
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 313, in 'calling callback function'
  File "C:\Python27\lib\site-packages\rtree\index.py", line 701, in py_next_item
    p_id[0], coordinates, obj = next(stream_iter)
TypeError: 'int' object is not iterable
Traceback (most recent call last):
  Python Shell, prompt 4, line 1
  File "C:\Python27\Lib\site-packages\rtree\index.py", line 266, in __init__
    self.handle = self._create_idx_from_stream(stream)
  File "C:\Python27\Lib\site-packages\rtree\index.py", line 730, in _create_idx_from_stream
    return IndexStreamHandle(self.properties.handle, stream)
  File "C:\Python27\Lib\site-packages\rtree\index.py", line 856, in __init__
    self._ptr = self._create(*args, **kwargs)
  File "C:\Python27\Lib\site-packages\rtree\core.py", line 28, in check_void
    raise RTreeError(msg)
rtree.core.RTreeError: Error in "Index_CreateWithStream": IllegalArgumentExc

**Comment by sgillies** [comment]
Your `stream` object is not a stream of items, it is a single item. To add a single item to the index, use `Index.insert()`: http://toblerity.org/rtree/class.html#rtree.index.Index.insert.

The stream loading documentation is misleading. You must pass a sequence of items. The following should work.

`rtree.index.Index([(8, (-3.5731852365209757, 0.7485694484767316, -2.9501297095816534, 1.5179486218942282), None)])`
