### ISSUE TITLE
Issue while indexing

### ISSUE THREAD

**Issue by GISConsortium** [Toblerity/rtree#95]
from rtree import index
idx= index.Index((7, (-3.5731852365209757, 0.7485694484767316, -2.9501297095816534, 1.5179486218942282), None))

Error:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 313, in 'calling callback function'
  File "C:\Python27\lib\site-packages\rtree\index.py", line 699, in py_next_item
    p_id[0], coordinates, obj = next(stream_iter)
TypeError: 'int' object is not iterable
Traceback (most recent call last):
  Python Shell, prompt 5, line 1
  File "C:\Python27\Lib\site-packages\rtree\index.py", line 264, in __init__
    self.handle = self._create_idx_from_stream(stream)
  File "C:\Python27\Lib\site-packages\rtree\index.py", line 728, in _create_idx_from_stream
    return IndexStreamHandle(self.properties.handle, stream)
  File "C:\Python27\Lib\site-packages\rtree\index.py", line 854, in __init__
    self._ptr = self._create(*args, **kwargs)
  File "C:\Python27\Lib\site-packages\rtree\core.py", line 28, in check_void
    raise RTreeError(msg)
rtree.core.RTreeError: Error in "Index_CreateWithStream": IllegalArgumentException: RTree::BulkLoader::bulkLoadUsingSTR: Empty data stream given.

**Comment by sgillies** [comment]
This is the same as #94. See that one for help. Adding duplicate issues does not do any good.
