### ISSUE TITLE
Index stream error

### ISSUE THREAD

**Issue by GISConsortium** [Toblerity/rtree#96]
import rtree
ridx = rtree.index.Index( [(0,(0,0,10,10),None), (1,(0,0,10,10),None)] )

I am facing this issue while creating index on my data.

Traceback (most recent call last):
File "_ctypes/callbacks.c", line 313, in 'calling callback function'
File "C:\Python27\lib\site-packages\rtree\index.py", line 717, in py_next_item
p_dimension[0] = dimension
ValueError: NULL pointer access
Traceback (most recent call last):
Python Shell, prompt 3, line 1
File "C:\Python27\Lib\site-packages\rtree\index.py", line 264, in init
self.handle = self._create_idx_from_stream(stream)
File "C:\Python27\Lib\site-packages\rtree\index.py", line 728, in _create_idx_from_stream
return IndexStreamHandle(self.properties.handle, stream)
File "C:\Python27\Lib\site-packages\rtree\index.py", line 854, in init
self._ptr = self._create(*args, **kwargs)
File "C:\Python27\Lib\site-packages\rtree\core.py", line 28, in check_void
raise RTreeError(msg)
rtree.core.RTreeError: Error in "Index_CreateWithStream": IllegalArgumentException: RTree::BulkLoader::bulkLoadUsingSTR: Empty data stream given.

**Comment by sgillies** [comment]
@GISConsortium because the project has long had tests of index population, 
https://github.com/Toblerity/rtree/blob/master/tests/test_index.py, and no other such reports, I suspect that you are having a packaging or installation problem.

Unless you tell us the following information we can only guess at your problem.

1. The source of the rtree package and libspatialindex library you installed
2. The versions of the software above
3. Python version
4. Operating system and version (Windows, apparently)

**Comment by hobu** [comment]
@GISConsortium please stop filing tickets in this repository.
