### ISSUE TITLE
issue while performing spatial join operation

### ISSUE THREAD

**Issue by shreeprem4u** [Toblerity/rtree#98]
Traceback (most recent call last):
  File "join.py", line 2, in <module>
    import geopandas as gpd
  File "/usr/local/lib/python2.7/dist-packages/geopandas/__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "/usr/local/lib/python2.7/dist-packages/geopandas/geoseries.py", line 12, in <module>
    from geopandas.base import GeoPandasBase, _series_unary_op, _CoordinateIndexer
  File "/usr/local/lib/python2.7/dist-packages/geopandas/base.py", line 14, in <module>
    from rtree.core import RTreeError
  File "/usr/local/lib/python2.7/dist-packages/rtree/__init__.py", line 1, in <module>
    from .index import Rtree
  File "/usr/local/lib/python2.7/dist-packages/rtree/index.py", line 5, in <module>
    from . import core
  File "/usr/local/lib/python2.7/dist-packages/rtree/core.py", line 125, in <module>
    raise OSError("Could not find libspatialindex_c library file")
OSError: Could not find libspatialindex_c library file

**Comment by sgillies** [comment]
First you must install the libspatialindex_c library. Get it from your system's package manager or build it from source following the instructions at http://toblerity.org/rtree/install.html#installation.
